### PR TITLE
Example in readme and UPM

### PR DESCRIPTION
**Pull request by popcron**
Im aware that a UPM related pr was already opened and then closed in #5, the closing comment stated that there are too many changes. So ill describe the changes here because the file change log looks bigger than what was actually done.
* package.json was added
  * All information here is based on whats already on the upstream repo
* Directories were moved up
  * Core, DefaultAttributes, DefaultUI are at the root now
* SerializeReferenceUIExample was renamed to Samples~
  * This allows the example to be seen by UPM as samples that can be imported (image below)
* The readme was updated to include instructions to install and a clear example of how to use and implement

example

### CODE REVIEW

**Comment by popcron** [comment]
At the moment, the git url in the installation to add the package is pointed at my fork, It'll be changed so that it points to this repo once it gets merged.

**Comment by DasOhmoff** [comment]
This would be a great addition! Please merge!

**Comment by rhys-vdw** [comment]
Any chance of this getting merged? I'd like to try out the library.

**Comment by TextusGames** [comment]
Thanks for PR! 
And sorry for that it has taken so long to merge it.

**Pull request merged**
